### ISSUE TITLE
Versions 0.5.5, 0.5.6 throw warnings in JRuby.

### ISSUE THREAD

**Issue by alanpeabody** [tempodb/tempodb-ruby#20]
I tracked the issue down to:

https://github.com/tempodb/tempodb-ruby/blob/master/lib/tempodb/client.rb#L255

Looks like JRuby does not use the 'N' argument and just ignores it:

`warning: encoding option is ignored - N`

**Comment by plainlystated** [comment]
Great, thanks for the report. I'll have a look at this and get it fixed for jruby

**Comment by plainlystated** [comment]
Fixed in 0.5.7
