### ISSUE TITLE
Setting port=443 and secure=true causes error

### ISSUE THREAD

**Issue by ajcronk** [tempodb/tempodb-ruby#6]
"I get an error when I use https (port=443, secure=true) . I think it's a bug. "

sinatra.error   
# <IOError: use_ssl value changed, but session already started>

This relates to:
https://github.com/tempodb/tempodb-ruby/blame/master/lib/tempodb.rb
92e43cf4 » myagley 
2012-09-06Fixing indenting  290  def do_http(uri, request) # :nodoc:
5d158fac » plainlystated 
2012-11-26support HTTP keepalive    291  if @http.nil?
292  @http = Net::HTTP.start(uri.host, uri.port)
293  @http.use_ssl = @secure
294  @http.verify_mode = OpenSSL::SSL::VERIFY_PEER
295  @http.ca_file = TempoDB::TRUSTED_CERT_FILE
296  end

The error is described here:

http://apidock.com/ruby/Net/HTTP/use_ssl%3D
use_ssl=(flag) public
Turn on/off SSL. This flag must be set before starting session. If you change use_ssl value after session started, aNet::HTTP object raises IOError

**Comment by plainlystated** [comment]
fixed in 0.5.2
